# Generated by Django 4.2.2 on 2023-06-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_rename_todo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
